Improve comments, run with bazel test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -36,8 +36,8 @@ jobs:
           python3 test.py -vvv
 
   small_test:
-    # Test if code runs successfully against a small project
-    name: Small Project Test
+    # Test the bazel rules introduced by repository on an independent open-source project.
+    name: Test On Small Project
     runs-on: ubuntu-24.04
 
     steps:
@@ -51,12 +51,14 @@ jobs:
         run:  |
           sh .github/workflows/patch-test-proj.sh ${{ github.repository }} ${{ github.ref }}
 
+      # Running bazel with test will signal failure because CodeChecker found problems
       - name: Run Monolithic Bazel CodeChecker
         run: |
           cd test_project
-          bazel build :codechecker_test
+          bazel test :codechecker_test || [ $? -eq 3 ] && exit 0 || exit $?
 
-      - name: Run Distributed Bazel CodeChecker
+      # Running bazel with test will signal failure because CodeChecker found problems
+      - name: Run Per File Bazel CodeChecker
         run: |
           cd test_project
-          bazel build :code_checker_test
+          bazel test :code_checker_test || [ $? -eq 3 ] && exit 0 || exit $?
